version: '2'
services:
  shoppingcart-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shoppingcartdb
      - MYSQL_USER=anotherroot
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
  shoppingcart-app:
    image: vaibhawmishra/shopping-cart-docker
    restart: on-failure
    depends_on:
      - shoppingcart-mysql
    ports:
      - '8080:8080'
